{
    "blue1": self.sprite_dict["playerLife1_blue"],
    "green1": self.sprite_dict["playerLife1_green"],
    "orange1": self.sprite_dict["playerLife1_orange"],
    "red1": self.sprite_dict["playerLife1_red"],
    "blue2": self.sprite_dict["playerLife2_blue"],
    "green2": self.sprite_dict["playerLife2_green"],
    "orange2": self.sprite_dict["playerLife2_orange"],
    "red2": self.sprite_dict["playerLife2_red"],
    "blue3": self.sprite_dict["playerLife3_blue"],
    "green3": self.sprite_dict["playerLife3_green"],
    "orange3": self.sprite_dict["playerLife3_orange"],
    "red3": self.sprite_dict["playerLife3_red"],
}

{
    "ship1_blue": self.sprite_dict["playerShip1_blue"],
    "ship1_damage1": self.sprite_dict["playerShip1_damage1"],
    "ship1_damage2": self.sprite_dict["playerShip1_damage2"],
    "ship1_damage3": self.sprite_dict["playerShip1_damage3"],
    "ship1_green": self.sprite_dict["playerShip1_green"],
    "ship1_orange": self.sprite_dict["playerShip1_orange"],
    "ship1_red": self.sprite_dict["playerShip1_red"],
    "ship2_blue": self.sprite_dict["playerShip2_blue"],
    "ship2_damage1": self.sprite_dict["playerShip2_damage1"],
    "ship2_damage2": self.sprite_dict["playerShip2_damage2"],
    "ship2_damage3": self.sprite_dict["playerShip2_damage3"],
    "ship2_green": self.sprite_dict["playerShip2_green"],
    "ship2_orange": self.sprite_dict["playerShip2_orange"],
    "ship2_red": self.sprite_dict["playerShip2_red"],
    "ship3_blue": self.sprite_dict["playerShip3_blue"],
    "ship3_damage1": self.sprite_dict["playerShip3_damage1"],
    "ship3_damage2": self.sprite_dict["playerShip3_damage2"],
    "ship3_damage3": self.sprite_dict["playerShip3_damage3"],
    "ship3_green": self.sprite_dict["playerShip3_green"],
    "ship3_orange": self.sprite_dict["playerShip3_orange"],
    "ship3_red": self.sprite_dict["playerShip3_red"],
}
